version: '3'
services:
  database:
    image: postgres:12-alpine
    container_name: postgres12_simplebank
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"

